apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prometheus.configmap_name }}
  labels:
    app: prometheus
data:
  config.yaml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanager:9093
    rule_files: []
      # - "first_rules.yml"
      # - "second_rules.yml"
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
        - targets: ["prometheus:9090"]
      {{ if .Values.firestarter.enabled }}
      - job_name: "firestarter"
        static_configs:
        - targets: ["firestarter:9100"]
      {{ end }}
      {{ if .Values.node-exporter.enabled }}
      - job_name: "node-exporter"
        static_configs:
        - targets: ["node-exporter:9100"]
      {{ end }}


