apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {{ .Values.prometheus.image }}:{{ .Values.prometheus.tag }}
        volumeMounts:
        - name: {{ .Values.prometheus.configmap_name }}
          mountPath: /etc/prometheus
      volumes:
      - name: {{ .Values.prometheus.configmap_name }}
        configMap:
          name: {{ .Values.prometheus.configmap_name }}
---
{{ if .Values.firestarter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firestarter
  labels:
    app: firestarter
    role: exporter
spec:
  replicas: 1
  selector:
    app: firestarter
  template:
    metadata:
      labels:
        app: firestarter
        role: exporter
    spec:
      containers:
      - name: firestarter
        image: {{ .Values.firestarter.image }}:{{ .Values.firestarter.tag }}
{{ end }}
---
{{ if .Values.node-exporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-exporter
  labels:
    app: node-exporter
    role: exporter
spec:
  replicas: 1
  selector:
    app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
        role: exporter
    spec:
      containers:
      - name: node-exporter
        image: {{ .Values.node-exporter.image }}:{{ .Values.firestarter.tag }}
        args: {{ .Values.node-exporter.args }}
{{ end }}

