version: 2.0
jobs:
  build:
    docker:
    - image: golang:1.14
    steps:
    - checkout
    - run:
        name: "Download dependencies"
        command: go get -v -t -d ./...
    - run:
        name: "Build"
        command: go build -v .
